# Generated by Django 6.1.1 on 2026-09-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('headline_en', models.CharField(max_length=255)),
                ('headline_fr', models.CharField(max_length=255)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_fr', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='owner_profile_single_row', violation_error_message='There is a single profile.'), models.CheckConstraint(condition=models.Q(models.Q(('bio_en', ''), ('bio_fr', '')), models.Q(models.Q(('bio_en', ''), _negated=True), models.Q(('bio_fr', ''), _negated=True)), _connector='OR'), name='owner_profile_bio_translated', violation_error_message='Fill in every language, or leave them all empty.')],
            },
        ),
    ]
