# Generated by Django 6.1.1 on 2026-10-05 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("website", "Website"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        max_length=500,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(https?://|mailto:)",
                                message="Enter a URL starting with https://, http:// or mailto:.",
                            )
                        ],
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
