# Generated by Django 6.1.2 on 2026-10-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owner", "0002_contactlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="desired_role_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="desired_role_fr",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("desired_role_en", ""), ("desired_role_fr", "")),
                    models.Q(
                        models.Q(("desired_role_en", ""), _negated=True),
                        models.Q(("desired_role_fr", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="owner_profile_desired_role_translated",
                violation_error_message="Fill in every language, or leave them all empty.",
            ),
        ),
    ]
