# Generated by Django 6.1.1 on 2026-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='certification',
            constraint=models.CheckConstraint(condition=models.Q(('expiration_date__isnull', True), ('expiration_date__gte', models.F('issue_date')), _connector='OR'), name='experience_certification_expiration_after_issue', violation_error_message='The expiration date cannot be before the issue date.'),
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='experience_education_end_after_start', violation_error_message='The end date cannot be before the start date.'),
        ),
        migrations.AddConstraint(
            model_name='professionalexperience',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='experience_professionalexperience_end_after_start', violation_error_message='The end date cannot be before the start date.'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='experience_project_end_after_start', violation_error_message='The end date cannot be before the start date.'),
        ),
        migrations.AddConstraint(
            model_name='specialization',
            constraint=models.CheckConstraint(condition=models.Q(('expiration_date__isnull', True), ('expiration_date__gte', models.F('issue_date')), _connector='OR'), name='experience_specialization_expiration_after_issue', violation_error_message='The expiration date cannot be before the issue date.'),
        ),
    ]
