# Generated by Django 6.1.1 on 2026-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0008_achievements_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values are shown first.')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'hobbies',
                'ordering': ['display_order', 'name_en'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('description_en', ''), ('description_fr', '')), models.Q(models.Q(('description_en', ''), _negated=True), models.Q(('description_fr', ''), _negated=True)), _connector='OR'), name='experience_hobby_description_translated', violation_error_message='Fill in every language, or leave them all empty.')],
            },
        ),
    ]
