# Generated by Django 6.1.1 on 2026-10-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0009_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values are shown first.')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('association', 'Association'), ('conference_organization', 'Conference organization'), ('other_event', 'Other event')], default='association', max_length=30)),
                ('organization', models.CharField(max_length=255)),
                ('role_en', models.CharField(max_length=255)),
                ('role_fr', models.CharField(max_length=255)),
                ('location_en', models.CharField(blank=True, max_length=255)),
                ('location_fr', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['display_order', '-start_date'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='experience_commitment_end_after_start', violation_error_message='The end date cannot be before the start date.'), models.CheckConstraint(condition=models.Q(models.Q(('description_en', ''), ('description_fr', '')), models.Q(models.Q(('description_en', ''), _negated=True), models.Q(('description_fr', ''), _negated=True)), _connector='OR'), name='experience_commitment_description_translated', violation_error_message='Fill in every language, or leave them all empty.'), models.CheckConstraint(condition=models.Q(models.Q(('location_en', ''), ('location_fr', '')), models.Q(models.Q(('location_en', ''), _negated=True), models.Q(('location_fr', ''), _negated=True)), _connector='OR'), name='experience_commitment_location_translated', violation_error_message='Fill in every language, or leave them all empty.')],
            },
        ),
    ]
