# Generated by Django 6.1.1 on 2026-10-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0010_commitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_en', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values are shown first.')),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('talk', 'Talk'), ('poster', 'Poster'), ('paper', 'Paper'), ('article', 'Article')], max_length=20)),
                ('title_en', models.CharField(max_length=255)),
                ('title_fr', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=500)),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['display_order', '-date'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('description_en', ''), ('description_fr', '')), models.Q(models.Q(('description_en', ''), _negated=True), models.Q(('description_fr', ''), _negated=True)), _connector='OR'), name='experience_scientificcommunication_description_translated', violation_error_message='Fill in every language, or leave them all empty.')],
            },
        ),
    ]
