# Generated by Django 6.1.1 on 2026-10-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experience", "0011_scientific_communication"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="note_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tag",
            name="note_fr",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="TagCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_fr", models.CharField(max_length=100)),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower values are shown first."
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="experience.tagcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tag categories",
                "ordering": ["position", "name_en"],
            },
        ),
        migrations.AddField(
            model_name="tag",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"parent__isnull": False},
                related_name="tags",
                to="experience.tagcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("note_en", ""), ("note_fr", "")),
                    models.Q(
                        models.Q(("note_en", ""), _negated=True),
                        models.Q(("note_fr", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="experience_tag_note_translated",
                violation_error_message="Fill in every language, or leave them all empty.",
            ),
        ),
    ]
